import p1 from '../assets/products/p1.jpg'
import p2 from '../assets/products/p2.jpg'
import p3 from '../assets/products/p3.jpg'
import p4 from '../assets/products/p4.jpg'
import p5 from '../assets/products/p5.jpg'
import p6 from '../assets/products/p6.jpg'
import p7 from '../assets/products/p7.jpg'
import p8 from '../assets/products/p8.jpg'
import p9 from '../assets/products/p9.jpg'
import p10 from '../assets/products/p10.jpg'
import p11 from '../assets/products/p11.jpg'
import p12 from '../assets/products/p12.jpg'
import p13 from '../assets/products/p13.jpg'
import p14 from '../assets/products/p14.jpg'
import p15 from '../assets/products/p15.jpg'
import p16 from '../assets/products/p16.jpg'    

export const products = [
    {image: p1, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p1, sub_p2: p2, sub_p3: p3, sub_p4: p4},
    {image: p2, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p2, sub_p2: p2, sub_p3: p2, sub_p4: p2},
    {image: p3, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p3, sub_p2: p3, sub_p3: p3, sub_p4: p3},
    {image: p4, type: 'Tee', price: '13', star: 4,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p4, sub_p2: p4, sub_p3: p4, sub_p4: p4},
    {image: p5, type: 'Tee', price: '13', star: 4,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p5, sub_p2: p5, sub_p3: p5, sub_p4: p5},
    {image: p6, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p6, sub_p2: p6, sub_p3: p6, sub_p4: p6},
    {image: p7, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p7, sub_p2: p7, sub_p3: p7, sub_p4: p7},
    {image: p8, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p8, sub_p2: p8, sub_p3: p8, sub_p4: p8},
    {image: p9, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p9: p9, sub_p2: p9, sub_p3: p9, sub_p4: p9},
    {image: p10, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p10, sub_p2: p10, sub_p3: p10, sub_p4: p10},
    {image: p11, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p11, sub_p2: p11, sub_p3: p11, sub_p4: p11},
    {image: p12, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p12, sub_p2: p12, sub_p3: p12, sub_p4: p12},
    {image: p13, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p13, sub_p2: p13, sub_p3: p13, sub_p4: p13},
    {image: p14, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p14, sub_p2: p14, sub_p3: p14, sub_p4: p14},
    {image: p15, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p15, sub_p2: p15, sub_p3: p15, sub_p4: p15},
    {image: p16, type: 'Tee', price: '13', star: 5,
    name: 'abc',
    Occasion: 'Casual',
    Color: 'Blue',
    Pattern: 'Color Block',
    Collar: 'Lapel Collar',
    Material: 'Polyester',
    SleevesLength: 'Long Sleeve',
    Brand: 'ChArmkpR',
    Thickness: 'Moderate',
    Season: 'Autumn',
    DesignElement: 'Patchwork, Button',
    FitType: 'Regular',
    Collection: 'Mensclo',
    sub_p1: p16, sub_p2: p16, sub_p3: p16, sub_p4: p16},
]